export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// These styles apply to every route in the application
import './globals.css'

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
